package com.smallintro.springboot.entity;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.springframework.hateoas.Link;
import org.springframework.hateoas.RepresentationModel;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel("This model is for technology information")
@Entity
@Table(name = "tb_technology")
public class Technology extends RepresentationModel<Technology> {
	@JsonIgnoreProperties("employees")
	@JsonFilter(value = "techFilter")

	@ApiModelProperty(notes = "Autogenerated unique Identity", position = 1)
	@Id
	@GeneratedValue
	private Integer techId;
	private String techName;
	private String catagory;
	private String description;

	@ManyToMany
	private List<Employee> employees;

	public Technology(Integer techId, String techName) {
		super();
		this.techId = techId;
		this.techName = techName;
	}

	public Technology() {
		super();
	}

	public Technology(Iterable<Link> initialLinks) {
		super(initialLinks);
		// TODO Auto-generated constructor stub
	}

	public Technology(Link initialLink) {
		super(initialLink);
		// TODO Auto-generated constructor stub
	}

	public Integer getTechId() {
		return techId;
	}

	public void setTechId(Integer techId) {
		this.techId = techId;
	}

	public String getTechName() {
		return techName;
	}

	public void setTechName(String techName) {
		this.techName = techName;
	}

	public String getCatagory() {
		return catagory;
	}

	public void setCatagory(String catagory) {
		this.catagory = catagory;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<Employee> getEmployees() {
		return employees;
	}

	public void setEmployees(List<Employee> employees) {
		this.employees = employees;
	}

}
