package com.smallintro.springboot.entity;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.springframework.hateoas.RepresentationModel;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel("This model is for technology information")
@Entity
@Table(name = "tb_technology")
public class Technology extends RepresentationModel<Technology>{

	@ApiModelProperty(notes="Autogenerated unique Identity",position=1)
	@Id
	@GeneratedValue
	private Integer techId;
	private String techName;
	private String catagoty;

	@ManyToMany
	private List<Employee> employee = new ArrayList<Employee>();

	public Integer getTechId() {
		return techId;
	}

	public void setTechId(Integer techId) {
		this.techId = techId;
	}

	public String getTechName() {
		return techName;
	}

	public void setTechName(String techName) {
		this.techName = techName;
	}

	public String getCatagoty() {
		return catagoty;
	}

	public void setCatagoty(String catagoty) {
		this.catagoty = catagoty;
	}

	public List<Employee> getEmployee() {
		return employee;
	}

	public void setEmployee(List<Employee> employee) {
		this.employee = employee;
	}

}
