spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: 
        - http://localhost:9081
  #Spring-boot admin
  boot:
    admin:
      client:
        url: http://127.0.0.1:9080
        instance:
          metadata:
            tags:
              environment: dev
zuul:
  prefix: /api
  routes:
    employee-service:
      path: /employee-service/**
      service-id: employee-service
    project-service:
      path: /project-service/**
      service-id: project-service
      
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  matrics:
    export: 
      jmx:
        enabled: true


