server:
  port: 9081
spring:
  application:
    name: config-servee
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active:
    - native
